apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rest-server-ingress
  namespace: music-separation
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx  
  rules:
  - host: rest.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rest-server
            port:
              number: 5000
